dist: trusty
language: node_js
node_js:
  - "8"
  - "10"
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test
  # XXX: needs investigation
  # currently disabled because not working on travis-ci
  # - yarn test:audio
  - yarn test:chrome
  - yarn test:vrs
